name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download NuGet dependencies
      run: dotnet restore SCLOCUA.csproj

    - name: Build solution
      run: msbuild SCLOCUA.csproj /p:Configuration=Release

    - name: Publish Release Artifact
      run: |
        Compress-Archive -Path bin/Release/* -DestinationPath SCLOCUA.zip
      if: success()
