name: Build and Release

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      release:
        description: 'Запустити реліз'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      run: |
        choco install dotnetfx --version 4.8.1 -y # Встановлюємо .NET Framework 4.8
        dotnet --list-sdks # Перевіряємо, що версія 4.8 встановлена
        dotnet --list-runtimes # Перевіряємо, що версія 4.8 встановлена
        dotnet --version # Перевіряємо версію .NET

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/Release/*.exe
        token: ${{ secrets.GH_TOKEN }}

    - name: Create Tag
      if: success()
      run: git tag -a v${{ github.run_number }} -m "Release v${{ github.run_number }}"
    
    - name: Push Tag
      if: success()
      run: git push origin v${{ github.run_number }}
